#define YY_parse_h_included
/*#define YY_USE_CLASS 
*/
/*  A Bison++ parser, made from structfe.y  */

 /* with Bison++ version bison++ Version 1.21.9-1, adapted from GNU bison by coetmeur@icdc.fr
Maintained by Magnus Ekdahl <magnus@debian.org>
  */


#line 1 "/usr/share/bison++/bison.cc"
/* -*-C-*-  Note some compilers choke on comments on `#line' lines.  */
/* Skeleton output parser for bison,
   Copyright (C) 1984, 1989, 1990 Bob Corbett and Richard Stallman

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 1, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.  

   As a special exception, when this file is copied by Bison++ into a
   Bison++ output file, you may use that output file without restriction.
   This special exception was added by the Free Software Foundation
   in version 1.24 of Bison, and has been in Bison++ since 1.21.9.  

*/

/* HEADER SECTION */
#if defined( _MSDOS ) || defined(MSDOS) || defined(__MSDOS__) 
 #define __MSDOS_AND_ALIKE
#endif

#if defined(_WINDOWS) && defined(_MSC_VER)
 #define __HAVE_NO_ALLOCA
 #define __MSDOS_AND_ALIKE
#endif

#ifndef alloca
 #if defined( __GNUC__)
  #define alloca __builtin_alloca

 #elif (!defined (__STDC__) && defined (sparc)) || defined (__sparc__) || defined (__sparc)  || defined (__sgi)
  #include <alloca.h>

 #elif defined (__MSDOS_AND_ALIKE)
  #include <malloc.h>
  #ifndef __TURBOC__
   /* MS C runtime lib */
   #define alloca _alloca
  #endif

 #elif defined(_AIX)
  /* pragma must be put before any C/C++ instruction !! */
  #pragma alloca
  #include <malloc.h>

 #elif defined(__hpux)
  #ifdef __cplusplus
   extern "C" {
     void *alloca (unsigned int);
   };
  #else /* not __cplusplus */
   void *alloca ();
  #endif /* not __cplusplus */

 #endif /* not _AIX  not MSDOS, or __TURBOC__ or _AIX, not sparc.  */
#endif /* alloca not defined.  */

#ifdef c_plusplus
 #ifndef __cplusplus
  #define __cplusplus
 #endif
#endif

#ifdef __cplusplus
 #ifndef YY_USE_CLASS
/*#warning "For C++ its recomended to use bison++, otherwise classes won't be generated"*/
 #endif
#else
 #ifndef __STDC__
  #define const
 #endif
 #ifdef YY_USE_CLASS
  #error "This is a C++ header generated by bison++, please use a C++ compiler!"
 #endif
#endif

#include <stdio.h>
#define YYBISON 1  

 #line 88 "/usr/share/bison++/bison.cc"
#line 1 "structfe.y"

#include "table_symboles.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

extern int yylineno;
void yyerror(const char *msg);
int yylex(void);
char * typesNames[]={"error","int","void","struct"};

int temp_counter = 0;
char* new_temp() {
    char* temp_name = (char*)malloc(10);
    snprintf(temp_name, 10, "t%d", temp_counter++);
    return temp_name;
}

#line 20 "structfe.y"
typedef union {
    int integer;
    char * code;
    char * str;
    char * varname;
    int intval;
    char* id;
    SymboleType symtype;
    Symbole* symptr;
    Node* nnode;
    LinkedList* ll;
    Element* elem;
} yy_parse_stype;
#define YY_parse_STYPE yy_parse_stype
#ifndef YY_USE_CLASS
#define YYSTYPE yy_parse_stype
#endif

#line 88 "/usr/share/bison++/bison.cc"
/* %{ and %header{ and %union, during decl */
#define YY_parse_BISON 1

#ifndef YY_parse_COMPATIBILITY
 #ifndef YY_USE_CLASS
  #define  YY_parse_COMPATIBILITY 1
 #else
  #define  YY_parse_COMPATIBILITY 0
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
 /* backward compatibility */
 #ifdef YYLTYPE
  #ifndef YY_parse_LTYPE
   #define YY_parse_LTYPE YYLTYPE
  #endif
 #endif
/* Testing alternative bison solution
   /#ifdef YYSTYPE*/
#ifndef YY_parse_STYPE 
   #define YY_parse_STYPE YYSTYPE
#endif
/*#endif*/
 #ifdef YYDEBUG
  #ifndef YY_parse_DEBUG
   #define  YY_parse_DEBUG YYDEBUG
  #endif
 #endif
 
 /* use goto to be compatible */
 #ifndef YY_parse_USE_GOTO
  #define YY_parse_USE_GOTO 1
 #endif
#endif

/* use no goto to be clean in C++ */
#ifndef YY_parse_USE_GOTO
 #define YY_parse_USE_GOTO 0
#endif

#ifndef YY_parse_PURE

 #line 130 "/usr/share/bison++/bison.cc"

#line 130 "/usr/share/bison++/bison.cc"
/*  YY_parse_PURE */
#endif

/* section apres lecture def, avant lecture grammaire S2 */

 #line 134 "/usr/share/bison++/bison.cc"

#line 134 "/usr/share/bison++/bison.cc"
/* prefix */
#ifndef YY_parse_DEBUG

 #line 136 "/usr/share/bison++/bison.cc"

#line 136 "/usr/share/bison++/bison.cc"
/* YY_parse_DEBUG */
#endif


#ifndef YY_parse_LSP_NEEDED

 #line 141 "/usr/share/bison++/bison.cc"

#line 141 "/usr/share/bison++/bison.cc"
 /* YY_parse_LSP_NEEDED*/
#endif



/* DEFAULT LTYPE*/
#ifdef YY_parse_LSP_NEEDED
#ifndef YY_parse_LTYPE
#ifndef BISON_YYLTYPE_ISDECLARED
#define BISON_YYLTYPE_ISDECLARED
typedef
  struct yyltype
    {
      int timestamp;
      int first_line;
      int first_column;
      int last_line;
      int last_column;
      char *text;
   }
  yyltype;

#endif
#define YY_parse_LTYPE yyltype
#endif
#endif
/* DEFAULT STYPE*/
      /* We used to use `unsigned long' as YY_parse_STYPE on MSDOS,
	 but it seems better to be consistent.
	 Most programs should declare their own type anyway.  */

#ifndef YY_parse_STYPE
#define YY_parse_STYPE int
#endif
/* DEFAULT MISCELANEOUS */
#ifndef YY_parse_PARSE
#define YY_parse_PARSE yyparse
#endif
#ifndef YY_parse_LEX
#define YY_parse_LEX yylex
#endif
#ifndef YY_parse_LVAL
#define YY_parse_LVAL yylval
#endif
#ifndef YY_parse_LLOC
#define YY_parse_LLOC yylloc
#endif
#ifndef YY_parse_CHAR
#define YY_parse_CHAR yychar
#endif
#ifndef YY_parse_NERRS
#define YY_parse_NERRS yynerrs
#endif
#ifndef YY_parse_DEBUG_FLAG
#define YY_parse_DEBUG_FLAG yydebug
#endif
#ifndef YY_parse_ERROR
#define YY_parse_ERROR yyerror
#endif

#ifndef YY_parse_PARSE_PARAM
 #ifndef YY_USE_CLASS
  #ifdef YYPARSE_PARAM
   #define YY_parse_PARSE_PARAM void* YYPARSE_PARAM 
  #else
   #ifndef __STDC__
    #ifndef __cplusplus
     #define YY_parse_PARSE_PARAM
    #endif
   #endif
  #endif
 #endif
 #ifndef YY_parse_PARSE_PARAM
  #define YY_parse_PARSE_PARAM void
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
/* backward compatibility */
#ifdef YY_parse_LTYPE
#ifndef YYLTYPE
#define YYLTYPE YY_parse_LTYPE
#else
/* WARNING obsolete !!! user defined YYLTYPE not reported into generated header */
#endif
#endif

/* Removed due to bison compabilityproblems
/#ifndef YYSTYPE
/#define YYSTYPE YY_parse_STYPE
/#else*/
/* WARNING obsolete !!! user defined YYSTYPE not reported into generated header */
/*#endif*/

#ifdef YY_parse_PURE
#  ifndef YYPURE
#    define YYPURE YY_parse_PURE
#  endif
#endif

#ifdef YY_parse_DEBUG
#  ifndef YYDEBUG
#    define YYDEBUG YY_parse_DEBUG 
#  endif
#endif

#ifndef YY_parse_ERROR_VERBOSE
 #ifdef YYERROR_VERBOSE
  #define YY_parse_ERROR_VERBOSE YYERROR_VERBOSE
 #endif
#endif

#ifndef YY_parse_LSP_NEEDED
#  ifdef YYLSP_NEEDED
#    define YY_parse_LSP_NEEDED YYLSP_NEEDED
#  endif
#endif

#endif

#ifndef YY_USE_CLASS
/* TOKEN C */

 #line 263 "/usr/share/bison++/bison.cc"
#define	IDENTIFIER	258
#define	CONSTANT	259
#define	SIZEOF	260
#define	PTR_OP	261
#define	LE_OP	262
#define	GE_OP	263
#define	EQ_OP	264
#define	NE_OP	265
#define	AND_OP	266
#define	OR_OP	267
#define	EXTERN	268
#define	INT	269
#define	VOID	270
#define	STRUCT	271
#define	IF	272
#define	ELSE	273
#define	WHILE	274
#define	FOR	275
#define	RETURN	276
#define	THEN	277


#line 263 "/usr/share/bison++/bison.cc"
 /* #defines tokens */
#else
/* CLASS */
#ifndef YY_parse_CLASS
#define YY_parse_CLASS parse
#endif
#ifndef YY_parse_INHERIT
#define YY_parse_INHERIT
#endif
#ifndef YY_parse_MEMBERS
#define YY_parse_MEMBERS 
#endif
#ifndef YY_parse_LEX_BODY
#define YY_parse_LEX_BODY  
#endif
#ifndef YY_parse_ERROR_BODY
#define YY_parse_ERROR_BODY  
#endif
#ifndef YY_parse_CONSTRUCTOR_PARAM
#define YY_parse_CONSTRUCTOR_PARAM
#endif
#ifndef YY_parse_CONSTRUCTOR_CODE
#define YY_parse_CONSTRUCTOR_CODE
#endif
#ifndef YY_parse_CONSTRUCTOR_INIT
#define YY_parse_CONSTRUCTOR_INIT
#endif
/* choose between enum and const */
#ifndef YY_parse_USE_CONST_TOKEN
#define YY_parse_USE_CONST_TOKEN 0
/* yes enum is more compatible with flex,  */
/* so by default we use it */ 
#endif
#if YY_parse_USE_CONST_TOKEN != 0
#ifndef YY_parse_ENUM_TOKEN
#define YY_parse_ENUM_TOKEN yy_parse_enum_token
#endif
#endif

class YY_parse_CLASS YY_parse_INHERIT
{
public: 
#if YY_parse_USE_CONST_TOKEN != 0
/* static const int token ... */

 #line 307 "/usr/share/bison++/bison.cc"
static const int IDENTIFIER;
static const int CONSTANT;
static const int SIZEOF;
static const int PTR_OP;
static const int LE_OP;
static const int GE_OP;
static const int EQ_OP;
static const int NE_OP;
static const int AND_OP;
static const int OR_OP;
static const int EXTERN;
static const int INT;
static const int VOID;
static const int STRUCT;
static const int IF;
static const int ELSE;
static const int WHILE;
static const int FOR;
static const int RETURN;
static const int THEN;


#line 307 "/usr/share/bison++/bison.cc"
 /* decl const */
#else
enum YY_parse_ENUM_TOKEN { YY_parse_NULL_TOKEN=0

 #line 310 "/usr/share/bison++/bison.cc"
	,IDENTIFIER=258
	,CONSTANT=259
	,SIZEOF=260
	,PTR_OP=261
	,LE_OP=262
	,GE_OP=263
	,EQ_OP=264
	,NE_OP=265
	,AND_OP=266
	,OR_OP=267
	,EXTERN=268
	,INT=269
	,VOID=270
	,STRUCT=271
	,IF=272
	,ELSE=273
	,WHILE=274
	,FOR=275
	,RETURN=276
	,THEN=277


#line 310 "/usr/share/bison++/bison.cc"
 /* enum token */
     }; /* end of enum declaration */
#endif
public:
 int YY_parse_PARSE (YY_parse_PARSE_PARAM);
 virtual void YY_parse_ERROR(char *msg) YY_parse_ERROR_BODY;
#ifdef YY_parse_PURE
#ifdef YY_parse_LSP_NEEDED
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL,YY_parse_LTYPE *YY_parse_LLOC) YY_parse_LEX_BODY;
#else
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL) YY_parse_LEX_BODY;
#endif
#else
 virtual int YY_parse_LEX() YY_parse_LEX_BODY;
 YY_parse_STYPE YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
 YY_parse_LTYPE YY_parse_LLOC;
#endif
 int   YY_parse_NERRS;
 int    YY_parse_CHAR;
#endif
#if YY_parse_DEBUG != 0
 int YY_parse_DEBUG_FLAG;   /*  nonzero means print parse trace     */
#endif
public:
 YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM);
public:
 YY_parse_MEMBERS 
};
/* other declare folow */
#if YY_parse_USE_CONST_TOKEN != 0

 #line 341 "/usr/share/bison++/bison.cc"
const int YY_parse_CLASS::IDENTIFIER=258;
const int YY_parse_CLASS::CONSTANT=259;
const int YY_parse_CLASS::SIZEOF=260;
const int YY_parse_CLASS::PTR_OP=261;
const int YY_parse_CLASS::LE_OP=262;
const int YY_parse_CLASS::GE_OP=263;
const int YY_parse_CLASS::EQ_OP=264;
const int YY_parse_CLASS::NE_OP=265;
const int YY_parse_CLASS::AND_OP=266;
const int YY_parse_CLASS::OR_OP=267;
const int YY_parse_CLASS::EXTERN=268;
const int YY_parse_CLASS::INT=269;
const int YY_parse_CLASS::VOID=270;
const int YY_parse_CLASS::STRUCT=271;
const int YY_parse_CLASS::IF=272;
const int YY_parse_CLASS::ELSE=273;
const int YY_parse_CLASS::WHILE=274;
const int YY_parse_CLASS::FOR=275;
const int YY_parse_CLASS::RETURN=276;
const int YY_parse_CLASS::THEN=277;


#line 341 "/usr/share/bison++/bison.cc"
 /* const YY_parse_CLASS::token */
#endif
/*apres const  */
YY_parse_CLASS::YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM) YY_parse_CONSTRUCTOR_INIT
{
#if YY_parse_DEBUG != 0
YY_parse_DEBUG_FLAG=0;
#endif
YY_parse_CONSTRUCTOR_CODE;
};
#endif

 #line 352 "/usr/share/bison++/bison.cc"


#define	YYFINAL		140
#define	YYFLAG		-32768
#define	YYNTBASE	37

#define YYTRANSLATE(x) ((unsigned)(x) <= 277 ? yytranslate[x] : 69)

static const char yytranslate[] = {     0,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,    26,     2,    23,
    24,    27,    30,    25,    28,     2,    29,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,    34,    31,
    33,    32,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,    35,     2,    36,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     1,     2,     3,     4,     5,
     6,     7,     8,     9,    10,    11,    12,    13,    14,    15,
    16,    17,    18,    19,    20,    21,    22
};

#if YY_parse_DEBUG != 0
static const short yyprhs[] = {     0,
     0,     2,     4,     8,    10,    14,    19,    21,    25,    27,
    30,    32,    34,    36,    38,    42,    46,    48,    52,    56,
    58,    62,    66,    70,    74,    76,    80,    84,    86,    90,
    92,    96,    98,   102,   106,   110,   114,   118,   122,   125,
   127,   129,   131,   137,   142,   145,   147,   150,   154,   157,
   159,   161,   165,   170,   174,   176,   180,   183,   185,   187,
   189,   191,   193,   196,   200,   204,   209,   211,   213,   215,
   218,   220,   223,   225,   228,   234,   242,   248,   256,   259,
   263,   265,   268,   270,   272
};

static const short yyrhs[] = {     3,
     0,     4,     0,    23,    48,    24,     0,    37,     0,    38,
    23,    24,     0,    38,    23,    39,    24,     0,    48,     0,
    39,    25,    48,     0,    38,     0,    41,    40,     0,    26,
     0,    27,     0,    28,     0,    40,     0,    42,    27,    40,
     0,    42,    29,    40,     0,    42,     0,    43,    30,    42,
     0,    43,    28,    42,     0,    43,     0,    44,    31,    43,
     0,    44,    32,    43,     0,    44,     7,    43,     0,    44,
     8,    43,     0,    44,     0,    45,     9,    44,     0,    45,
    10,    44,     0,    45,     0,    46,    11,    45,     0,    46,
     0,    47,    12,    46,     0,    47,     0,    40,    33,    48,
     0,    48,    32,    48,     0,    48,    31,    48,     0,    48,
     7,    48,     0,    48,     8,    48,     0,    50,    52,    34,
     0,    13,    51,     0,    51,     0,    15,     0,    14,     0,
    16,     3,    35,     0,    36,     0,    16,    35,     0,    36,
     0,    16,     3,     0,     0,     0,     0,     0,     0,    51,
    52,    34,     0,    27,    53,     0,    53,     0,     3,     0,
    23,    52,    24,     0,    53,    23,    54,    24,     0,    53,
    23,    24,     0,    55,     0,    54,    25,    55,     0,    50,
    52,     0,    57,     0,    62,     0,    63,     0,    64,     0,
    65,     0,    58,    59,     0,    58,    61,    59,     0,    58,
    60,    59,     0,    58,    60,    61,    59,     0,    35,     0,
    36,     0,    49,     0,    60,    49,     0,    56,     0,    61,
    56,     0,    34,     0,    48,    34,     0,    17,    23,    48,
    24,    56,     0,    17,    23,    48,    24,    56,    18,    56,
     0,    19,    23,    48,    24,    56,     0,    20,    23,    62,
    62,    48,    24,    56,     0,    21,    34,     0,    21,    48,
    34,     0,    67,     0,    66,    67,     0,    68,     0,    49,
     0,    50,    52,    57,     0
};

#endif

#if (YY_parse_DEBUG != 0) || defined(YY_parse_ERROR_VERBOSE) 
static const short yyrline[] = { 0,
    50,    56,    62,    68,    71,    74,    81,    84,    92,    95,
   106,   107,   108,   112,   115,   123,   134,   137,   145,   156,
   159,   167,   175,   183,   195,   198,   201,   207,   210,   216,
   219,   225,   228,   232,   236,   240,   244,   252,   259,   262,
   268,   274,   283,   289,   295,   304,   305,   309,   315,   319,
   325,   331,   334,   337,   344,   345,   349,   356,   357,   358,
   359,   360,   364,   365,   366,   367,   371,   377,   384,   385,
   389,   390,   394,   395,   399,   402,   409,   410,   414,   417,
   423,   424,   428,   429,   433
};

static const char * const yytname[] = {   "$","error","$illegal.","IDENTIFIER",
"CONSTANT","SIZEOF","PTR_OP","LE_OP","GE_OP","EQ_OP","NE_OP","AND_OP","OR_OP",
"EXTERN","INT","VOID","STRUCT","IF","ELSE","WHILE","FOR","RETURN","THEN","'('",
"')'","','","'&'","'*'","'-'","'/'","'+'","'<'","'>'","'='","';'","'{'","'}'",
"primary_expression","postfix_expression","argument_expression_list","unary_expression",
"unary_operator","multiplicative_expression","additive_expression","relational_expression",
"equality_expression","logical_and_expression","logical_or_expression","expression",
"declaration","declaration_specifiers","type_specifier","declarator","direct_declarator",
"parameter_list","parameter_declaration","statement","compound_statement","open_accol",
"close_accol","declaration_list","statement_list","expression_statement","selection_statement",
"iteration_statement","jump_statement","program","external_declaration","function_definition",
"program"
};
#endif

static const short yyr1[] = {     0,
    37,    37,    37,    38,    38,    38,    39,    39,    40,    40,
    41,    41,    41,    42,    42,    42,    43,    43,    43,    44,
    44,    44,    44,    44,    45,    45,    45,    46,    46,    47,
    47,    48,    48,    48,    48,    48,    48,    49,    50,    50,
    51,    51,    -1,    -1,    -1,    -1,    -1,    -1,    52,    52,
    53,    53,    53,    53,    54,    54,    55,    56,    56,    56,
    56,    56,    57,    57,    57,    57,    58,    59,    60,    60,
    61,    61,    62,    62,    63,    63,    64,    64,    65,    65,
    66,    66,    67,    67,    68
};

static const short yyr2[] = {     0,
     1,     1,     3,     1,     3,     4,     1,     3,     1,     2,
     1,     1,     1,     1,     3,     3,     1,     3,     3,     1,
     3,     3,     3,     3,     1,     3,     3,     1,     3,     1,
     3,     1,     3,     3,     3,     3,     3,     3,     2,     1,
     1,     1,     5,     4,     2,     1,     2,     3,     2,     1,
     1,     3,     4,     3,     1,     3,     2,     1,     1,     1,
     1,     1,     2,     3,     3,     4,     1,     1,     1,     2,
     1,     2,     1,     2,     5,     7,     5,     7,     2,     3,
     1,     2,     1,     1,     3
};

static const short yydefact[] = {     0,
     0,    42,    41,    84,     0,    40,     0,    81,    83,    39,
    51,     0,     0,     0,    50,    82,     0,    49,    38,    67,
    85,     0,     0,    52,     1,     2,     0,     0,     0,     0,
     0,    11,    12,    13,    73,    68,     4,     9,    14,     0,
    17,    20,    25,    28,    30,    32,     0,    69,     0,    71,
    58,    63,     0,     0,    59,    60,    61,    62,    54,     0,
     0,    55,     0,     0,     0,    79,     0,     0,     0,     0,
    10,     0,     0,     0,     0,     0,     0,     0,     0,     0,
     0,     0,     0,     0,     0,     0,     0,    74,     0,    70,
    65,     0,    72,    64,    57,    53,     0,     0,     0,     0,
    80,     3,     5,     0,     7,    33,    15,    16,    14,    19,
    18,    23,    24,    21,    22,    26,    27,    29,    31,    36,
    37,    35,    34,    66,    56,     0,     0,     0,     6,     0,
    75,    77,     0,     8,     0,     0,    76,    78,     0,     0
};

static const short yydefgoto[] = {    37,
    38,   104,    39,    40,    41,    42,    43,    44,    45,    46,
    47,     4,     5,     6,    14,    15,    61,    62,    50,    51,
    22,    52,    53,    54,    55,    56,    57,    58,     7,     8,
     9
};

static const short yypact[] = {   106,
    -1,-32768,-32768,-32768,     9,-32768,     8,-32768,-32768,-32768,
-32768,     9,    15,    -4,   -14,-32768,    26,   -14,-32768,-32768,
-32768,    88,     2,-32768,-32768,-32768,    63,    67,    81,   151,
   178,-32768,-32768,-32768,-32768,-32768,-32768,    83,    92,   178,
    60,    69,    21,    68,   120,   115,    12,-32768,     9,-32768,
-32768,-32768,    88,   109,-32768,-32768,-32768,-32768,-32768,     9,
    49,-32768,   178,   178,   163,-32768,    17,    64,   172,   178,
-32768,   178,   178,   178,   178,   178,   178,   178,   178,   178,
   178,   178,   178,   178,   178,   178,   178,-32768,   108,-32768,
-32768,   109,-32768,-32768,-32768,-32768,   106,    86,   185,   163,
-32768,-32768,-32768,   116,   131,   131,-32768,-32768,-32768,    60,
    60,    69,    69,    69,    69,    21,    21,    68,   120,   131,
   131,   131,   131,-32768,-32768,   130,   130,   178,-32768,   178,
   128,-32768,   195,   131,   130,   130,-32768,-32768,   148,-32768
};

static const short yypgoto[] = {-32768,
-32768,-32768,   -13,-32768,    85,     4,    89,    70,    78,-32768,
   -30,   -11,   -18,   167,    -2,   158,-32768,    75,   -51,   159,
-32768,   -47,-32768,   127,   -63,-32768,-32768,-32768,-32768,   176,
-32768
};


#define	YYLAST		227


static const short yytable[] = {    67,
    68,   100,    93,    49,    60,    91,    94,   139,    23,    17,
    48,    11,     2,     3,     1,     2,     3,    11,    84,    85,
     1,     2,     3,    84,    85,    59,    71,    76,    77,    19,
    20,    12,    98,    99,    49,    13,   128,    12,   105,   106,
    93,    90,    86,    87,   124,    88,    89,    86,    87,    24,
   101,    78,    79,   120,   121,   122,   123,    95,   107,   108,
   109,   109,   109,   109,   109,   109,   109,   109,   109,   109,
    84,    85,    96,    97,   131,   132,    80,    81,    60,   112,
   113,   114,   115,   137,   138,    63,    72,   102,    73,    64,
    25,    26,    84,    85,    86,    87,    74,   133,    75,   134,
     1,     2,     3,    65,    27,    69,    28,    29,    30,   126,
    31,    25,    26,    32,    33,    34,    86,    87,     1,     2,
     3,    35,    20,    36,    70,    27,    83,    28,    29,    30,
    82,    31,    25,    26,    32,    33,    34,    84,    85,   129,
   130,    19,    35,    20,    36,   135,    27,   140,    28,    29,
    30,   118,    31,    25,    26,    32,    33,    34,   110,   111,
   119,    86,    87,    35,    20,    25,    26,    10,   116,   117,
    18,   125,    21,    31,    25,    26,    32,    33,    34,    92,
    25,    26,    16,     0,    66,    31,     0,     0,    32,    33,
    34,    84,    85,     0,    31,   103,    35,    32,    33,    34,
    31,    84,    85,    32,    33,    34,     0,     0,   127,     0,
     0,     0,     0,     0,     0,    86,    87,     0,   136,     0,
     0,     0,     0,     0,     0,    86,    87
};

static const short yycheck[] = {    30,
    31,    65,    54,    22,    23,    53,    54,     0,    23,    12,
    22,     3,    14,    15,    13,    14,    15,     3,     7,     8,
    13,    14,    15,     7,     8,    24,    40,     7,     8,    34,
    35,    23,    63,    64,    53,    27,   100,    23,    69,    70,
    92,    53,    31,    32,    92,    34,    49,    31,    32,    24,
    34,    31,    32,    84,    85,    86,    87,    60,    72,    73,
    74,    75,    76,    77,    78,    79,    80,    81,    82,    83,
     7,     8,    24,    25,   126,   127,     9,    10,    97,    76,
    77,    78,    79,   135,   136,    23,    27,    24,    29,    23,
     3,     4,     7,     8,    31,    32,    28,   128,    30,   130,
    13,    14,    15,    23,    17,    23,    19,    20,    21,    24,
    23,     3,     4,    26,    27,    28,    31,    32,    13,    14,
    15,    34,    35,    36,    33,    17,    12,    19,    20,    21,
    11,    23,     3,     4,    26,    27,    28,     7,     8,    24,
    25,    34,    34,    35,    36,    18,    17,     0,    19,    20,
    21,    82,    23,     3,     4,    26,    27,    28,    74,    75,
    83,    31,    32,    34,    35,     3,     4,     1,    80,    81,
    13,    97,    14,    23,     3,     4,    26,    27,    28,    53,
     3,     4,     7,    -1,    34,    23,    -1,    -1,    26,    27,
    28,     7,     8,    -1,    23,    24,    34,    26,    27,    28,
    23,     7,     8,    26,    27,    28,    -1,    -1,    24,    -1,
    -1,    -1,    -1,    -1,    -1,    31,    32,    -1,    24,    -1,
    -1,    -1,    -1,    -1,    -1,    31,    32
};

#line 352 "/usr/share/bison++/bison.cc"
 /* fattrs + tables */

/* parser code folow  */


/* This is the parser code that is written into each bison parser
  when the %semantic_parser declaration is not specified in the grammar.
  It was written by Richard Stallman by simplifying the hairy parser
  used when %semantic_parser is specified.  */

/* Note: dollar marks section change
   the next  is replaced by the list of actions, each action
   as one case of the switch.  */ 

#if YY_parse_USE_GOTO != 0
/* 
 SUPRESSION OF GOTO : on some C++ compiler (sun c++)
  the goto is strictly forbidden if any constructor/destructor
  is used in the whole function (very stupid isn't it ?)
 so goto are to be replaced with a 'while/switch/case construct'
 here are the macro to keep some apparent compatibility
*/
#define YYGOTO(lb) {yy_gotostate=lb;continue;}
#define YYBEGINGOTO  enum yy_labels yy_gotostate=yygotostart; \
                     for(;;) switch(yy_gotostate) { case yygotostart: {
#define YYLABEL(lb) } case lb: {
#define YYENDGOTO } } 
#define YYBEGINDECLARELABEL enum yy_labels {yygotostart
#define YYDECLARELABEL(lb) ,lb
#define YYENDDECLARELABEL  };
#else
/* macro to keep goto */
#define YYGOTO(lb) goto lb
#define YYBEGINGOTO 
#define YYLABEL(lb) lb:
#define YYENDGOTO
#define YYBEGINDECLARELABEL 
#define YYDECLARELABEL(lb)
#define YYENDDECLARELABEL 
#endif
/* LABEL DECLARATION */
YYBEGINDECLARELABEL
  YYDECLARELABEL(yynewstate)
  YYDECLARELABEL(yybackup)
/* YYDECLARELABEL(yyresume) */
  YYDECLARELABEL(yydefault)
  YYDECLARELABEL(yyreduce)
  YYDECLARELABEL(yyerrlab)   /* here on detecting error */
  YYDECLARELABEL(yyerrlab1)   /* here on error raised explicitly by an action */
  YYDECLARELABEL(yyerrdefault)  /* current state does not do anything special for the error token. */
  YYDECLARELABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */
  YYDECLARELABEL(yyerrhandle)  
YYENDDECLARELABEL
/* ALLOCA SIMULATION */
/* __HAVE_NO_ALLOCA */
#ifdef __HAVE_NO_ALLOCA
int __alloca_free_ptr(char *ptr,char *ref)
{if(ptr!=ref) free(ptr);
 return 0;}

#define __ALLOCA_alloca(size) malloc(size)
#define __ALLOCA_free(ptr,ref) __alloca_free_ptr((char *)ptr,(char *)ref)

#ifdef YY_parse_LSP_NEEDED
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		    __ALLOCA_free(yyls,yylsa)+\
		   (num)); } while(0)
#else
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		   (num)); } while(0)
#endif
#else
#define __ALLOCA_return(num) do { return(num); } while(0)
#define __ALLOCA_alloca(size) alloca(size)
#define __ALLOCA_free(ptr,ref) 
#endif

/* ENDALLOCA SIMULATION */

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (YY_parse_CHAR = YYEMPTY)
#define YYEMPTY         -2
#define YYEOF           0
#define YYACCEPT        __ALLOCA_return(0)
#define YYABORT         __ALLOCA_return(1)
#define YYERROR         YYGOTO(yyerrlab1)
/* Like YYERROR except do call yyerror.
   This remains here temporarily to ease the
   transition to the new meaning of YYERROR, for GCC.
   Once GCC version 2 has supplanted version 1, this can go.  */
#define YYFAIL          YYGOTO(yyerrlab)
#define YYRECOVERING()  (!!yyerrstatus)
#define YYBACKUP(token, value) \
do                                                              \
  if (YY_parse_CHAR == YYEMPTY && yylen == 1)                               \
    { YY_parse_CHAR = (token), YY_parse_LVAL = (value);                 \
      yychar1 = YYTRANSLATE (YY_parse_CHAR);                                \
      YYPOPSTACK;                                               \
      YYGOTO(yybackup);                                            \
    }                                                           \
  else                                                          \
    { YY_parse_ERROR ("syntax error: cannot back up"); YYERROR; }   \
while (0)

#define YYTERROR        1
#define YYERRCODE       256

#ifndef YY_parse_PURE
/* UNPURE */
#define YYLEX           YY_parse_LEX()
#ifndef YY_USE_CLASS
/* If nonreentrant, and not class , generate the variables here */
int     YY_parse_CHAR;                      /*  the lookahead symbol        */
YY_parse_STYPE      YY_parse_LVAL;              /*  the semantic value of the */
				/*  lookahead symbol    */
int YY_parse_NERRS;                 /*  number of parse errors so far */
#ifdef YY_parse_LSP_NEEDED
YY_parse_LTYPE YY_parse_LLOC;   /*  location data for the lookahead     */
			/*  symbol                              */
#endif
#endif


#else
/* PURE */
#ifdef YY_parse_LSP_NEEDED
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL, &YY_parse_LLOC)
#else
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL)
#endif
#endif
#ifndef YY_USE_CLASS
#if YY_parse_DEBUG != 0
int YY_parse_DEBUG_FLAG;                    /*  nonzero means print parse trace     */
/* Since this is uninitialized, it does not stop multiple parsers
   from coexisting.  */
#endif
#endif



/*  YYINITDEPTH indicates the initial size of the parser's stacks       */

#ifndef YYINITDEPTH
#define YYINITDEPTH 200
#endif

/*  YYMAXDEPTH is the maximum size the stacks can grow to
    (effective only if the built-in stack extension method is used).  */

#if YYMAXDEPTH == 0
#undef YYMAXDEPTH
#endif

#ifndef YYMAXDEPTH
#define YYMAXDEPTH 10000
#endif


#if __GNUC__ > 1                /* GNU C and GNU C++ define this.  */
#define __yy_bcopy(FROM,TO,COUNT)       __builtin_memcpy(TO,FROM,COUNT)
#else                           /* not GNU C or C++ */

/* This is the most reliable way to avoid incompatibilities
   in available built-in functions on various systems.  */

#ifdef __cplusplus
static void __yy_bcopy (char *from, char *to, int count)
#else
#ifdef __STDC__
static void __yy_bcopy (char *from, char *to, int count)
#else
static void __yy_bcopy (from, to, count)
     char *from;
     char *to;
     int count;
#endif
#endif
{
  register char *f = from;
  register char *t = to;
  register int i = count;

  while (i-- > 0)
    *t++ = *f++;
}
#endif


int
#ifdef YY_USE_CLASS
 YY_parse_CLASS::
#endif
     YY_parse_PARSE(YY_parse_PARSE_PARAM)
#ifndef __STDC__
#ifndef __cplusplus
#ifndef YY_USE_CLASS
/* parameter definition without protypes */
YY_parse_PARSE_PARAM_DEF
#endif
#endif
#endif
{
  register int yystate;
  register int yyn;
  register short *yyssp;
  register YY_parse_STYPE *yyvsp;
  int yyerrstatus;      /*  number of tokens to shift before error messages enabled */
  int yychar1=0;          /*  lookahead token as an internal (translated) token number */

  short yyssa[YYINITDEPTH];     /*  the state stack                     */
  YY_parse_STYPE yyvsa[YYINITDEPTH];        /*  the semantic value stack            */

  short *yyss = yyssa;          /*  refer to the stacks thru separate pointers */
  YY_parse_STYPE *yyvs = yyvsa;     /*  to allow yyoverflow to reallocate them elsewhere */

#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE yylsa[YYINITDEPTH];        /*  the location stack                  */
  YY_parse_LTYPE *yyls = yylsa;
  YY_parse_LTYPE *yylsp;

#define YYPOPSTACK   (yyvsp--, yyssp--, yylsp--)
#else
#define YYPOPSTACK   (yyvsp--, yyssp--)
#endif

  int yystacksize = YYINITDEPTH;

#ifdef YY_parse_PURE
  int YY_parse_CHAR;
  YY_parse_STYPE YY_parse_LVAL;
  int YY_parse_NERRS;
#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE YY_parse_LLOC;
#endif
#endif

  YY_parse_STYPE yyval;             /*  the variable used to return         */
				/*  semantic values from the action     */
				/*  routines                            */

  int yylen;
/* start loop, in which YYGOTO may be used. */
YYBEGINGOTO

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Starting parse\n");
#endif
  yystate = 0;
  yyerrstatus = 0;
  YY_parse_NERRS = 0;
  YY_parse_CHAR = YYEMPTY;          /* Cause a token to be read.  */

  /* Initialize stack pointers.
     Waste one element of value and location stack
     so that they stay on the same level as the state stack.
     The wasted elements are never initialized.  */

  yyssp = yyss - 1;
  yyvsp = yyvs;
#ifdef YY_parse_LSP_NEEDED
  yylsp = yyls;
#endif

/* Push a new state, which is found in  yystate  .  */
/* In all cases, when you get here, the value and location stacks
   have just been pushed. so pushing a state here evens the stacks.  */
YYLABEL(yynewstate)

  *++yyssp = yystate;

  if (yyssp >= yyss + yystacksize - 1)
    {
      /* Give user a chance to reallocate the stack */
      /* Use copies of these so that the &'s don't force the real ones into memory. */
      YY_parse_STYPE *yyvs1 = yyvs;
      short *yyss1 = yyss;
#ifdef YY_parse_LSP_NEEDED
      YY_parse_LTYPE *yyls1 = yyls;
#endif

      /* Get the current used size of the three stacks, in elements.  */
      int size = yyssp - yyss + 1;

#ifdef yyoverflow
      /* Each stack pointer address is followed by the size of
	 the data in use in that stack, in bytes.  */
#ifdef YY_parse_LSP_NEEDED
      /* This used to be a conditional around just the two extra args,
	 but that might be undefined if yyoverflow is a macro.  */
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yyls1, size * sizeof (*yylsp),
		 &yystacksize);
#else
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yystacksize);
#endif

      yyss = yyss1; yyvs = yyvs1;
#ifdef YY_parse_LSP_NEEDED
      yyls = yyls1;
#endif
#else /* no yyoverflow */
      /* Extend the stack our own way.  */
      if (yystacksize >= YYMAXDEPTH)
	{
	  YY_parse_ERROR("parser stack overflow");
	  __ALLOCA_return(2);
	}
      yystacksize *= 2;
      if (yystacksize > YYMAXDEPTH)
	yystacksize = YYMAXDEPTH;
      yyss = (short *) __ALLOCA_alloca (yystacksize * sizeof (*yyssp));
      __yy_bcopy ((char *)yyss1, (char *)yyss, size * sizeof (*yyssp));
      __ALLOCA_free(yyss1,yyssa);
      yyvs = (YY_parse_STYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yyvsp));
      __yy_bcopy ((char *)yyvs1, (char *)yyvs, size * sizeof (*yyvsp));
      __ALLOCA_free(yyvs1,yyvsa);
#ifdef YY_parse_LSP_NEEDED
      yyls = (YY_parse_LTYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yylsp));
      __yy_bcopy ((char *)yyls1, (char *)yyls, size * sizeof (*yylsp));
      __ALLOCA_free(yyls1,yylsa);
#endif
#endif /* no yyoverflow */

      yyssp = yyss + size - 1;
      yyvsp = yyvs + size - 1;
#ifdef YY_parse_LSP_NEEDED
      yylsp = yyls + size - 1;
#endif

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Stack size increased to %d\n", yystacksize);
#endif

      if (yyssp >= yyss + yystacksize - 1)
	YYABORT;
    }

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Entering state %d\n", yystate);
#endif

  YYGOTO(yybackup);
YYLABEL(yybackup)

/* Do appropriate processing given the current state.  */
/* Read a lookahead token if we need one and don't already have one.  */
/* YYLABEL(yyresume) */

  /* First try to decide what to do without reference to lookahead token.  */

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yydefault);

  /* Not known => get a lookahead token if don't already have one.  */

  /* yychar is either YYEMPTY or YYEOF
     or a valid token in external form.  */

  if (YY_parse_CHAR == YYEMPTY)
    {
#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Reading a token: ");
#endif
      YY_parse_CHAR = YYLEX;
    }

  /* Convert token to internal form (in yychar1) for indexing tables with */

  if (YY_parse_CHAR <= 0)           /* This means end of input. */
    {
      yychar1 = 0;
      YY_parse_CHAR = YYEOF;                /* Don't call YYLEX any more */

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Now at end of input.\n");
#endif
    }
  else
    {
      yychar1 = YYTRANSLATE(YY_parse_CHAR);

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	{
	  fprintf (stderr, "Next token is %d (%s", YY_parse_CHAR, yytname[yychar1]);
	  /* Give the individual parser a way to print the precise meaning
	     of a token, for further debugging info.  */
#ifdef YYPRINT
	  YYPRINT (stderr, YY_parse_CHAR, YY_parse_LVAL);
#endif
	  fprintf (stderr, ")\n");
	}
#endif
    }

  yyn += yychar1;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != yychar1)
    YYGOTO(yydefault);

  yyn = yytable[yyn];

  /* yyn is what to do for this token type in this state.
     Negative => reduce, -yyn is rule number.
     Positive => shift, yyn is new state.
       New state is final state => don't bother to shift,
       just return success.
     0, or most negative number => error.  */

  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrlab);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrlab);

  if (yyn == YYFINAL)
    YYACCEPT;

  /* Shift the lookahead token.  */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting token %d (%s), ", YY_parse_CHAR, yytname[yychar1]);
#endif

  /* Discard the token being shifted unless it is eof.  */
  if (YY_parse_CHAR != YYEOF)
    YY_parse_CHAR = YYEMPTY;

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  /* count tokens shifted since error; after three, turn off error status.  */
  if (yyerrstatus) yyerrstatus--;

  yystate = yyn;
  YYGOTO(yynewstate);

/* Do the default action for the current state.  */
YYLABEL(yydefault)

  yyn = yydefact[yystate];
  if (yyn == 0)
    YYGOTO(yyerrlab);

/* Do a reduction.  yyn is the number of a rule to reduce with.  */
YYLABEL(yyreduce)
  yylen = yyr2[yyn];
  if (yylen > 0)
    yyval = yyvsp[1-yylen]; /* implement default value of the action */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      int i;

      fprintf (stderr, "Reducing via rule %d (line %d), ",
	       yyn, yyrline[yyn]);

      /* Print the symbols being reduced, and their result.  */
      for (i = yyprhs[yyn]; yyrhs[i] > 0; i++)
	fprintf (stderr, "%s ", yytname[yyrhs[i]]);
      fprintf (stderr, " -> %s\n", yytname[yyr1[yyn]]);
    }
#endif


 #line 839 "/usr/share/bison++/bison.cc"

  switch (yyn) {

case 1:
#line 50 "structfe.y"
{
        Element * e = malloc(sizeof(Element));
        e->type = TYPE_INT;
        e->code = yyvsp[0].id;
        yyval.elem = e;
    ;
    break;}
case 2:
#line 56 "structfe.y"
{
        Element * e = malloc(sizeof(Element));
        e->type = TYPE_INT;
        e->code = yyvsp[0].id;
        yyval.elem = e;
    ;
    break;}
case 3:
#line 62 "structfe.y"
{
        yyval.elem = yyvsp[-1].elem;
    ;
    break;}
case 4:
#line 68 "structfe.y"
{
        yyval.elem = yyvsp[0].elem;
    ;
    break;}
case 5:
#line 71 "structfe.y"
{
        yyval.elem = yyvsp[-2].elem;
    ;
    break;}
case 6:
#line 74 "structfe.y"
{
        printf("Yacc code 3adrs:%s(%s)\n", yyvsp[-3].elem->code, yyvsp[-1].elem->code);
        yyval.elem = yyvsp[-3].elem;
    ;
    break;}
case 7:
#line 81 "structfe.y"
{
        yyval.elem = yyvsp[0].elem;
    ;
    break;}
case 8:
#line 84 "structfe.y"
{
        yyval.elem = yyvsp[-2].elem;
        char * res = concat(yyvsp[-2].elem->code, concat(",", yyvsp[0].elem->code));
        yyval.elem->code = res;
    ;
    break;}
case 9:
#line 92 "structfe.y"
{
        yyval.elem = yyvsp[0].elem;
    ;
    break;}
case 10:
#line 95 "structfe.y"
{
        char * temp = new_temp();
        printf("Yacc code 3adrs:%s = %s%s;\n", temp, yyvsp[-1].id, yyvsp[0].elem->code);
        Element * e = malloc(sizeof(Element));
        e->type = yyvsp[0].elem->type;
        e->code = temp;
        yyval.elem = e;
    ;
    break;}
case 11:
#line 106 "structfe.y"
{ yyval.id = "&"; ;
    break;}
case 12:
#line 107 "structfe.y"
{ yyval.id = "*"; ;
    break;}
case 13:
#line 108 "structfe.y"
{ yyval.id = "-"; ;
    break;}
case 14:
#line 112 "structfe.y"
{
        yyval.elem = yyvsp[0].elem;
    ;
    break;}
case 15:
#line 115 "structfe.y"
{
        char * temp = new_temp();
        printf("Yacc code 3adrs:%s = %s * %s;\n", temp, yyvsp[-2].elem->code, yyvsp[0].elem->code);
        Element * e = malloc(sizeof(Element));
        e->type = TYPE_INT;
        e->code = temp;
        yyval.elem = e;
    ;
    break;}
case 16:
#line 123 "structfe.y"
{
        char * temp = new_temp();
        printf("Yacc code 3adrs:%s = %s / %s;\n", temp, yyvsp[-2].elem->code, yyvsp[0].elem->code);
        Element * e = malloc(sizeof(Element));
        e->type = TYPE_INT;
        e->code = temp;
        yyval.elem = e;
    ;
    break;}
case 17:
#line 134 "structfe.y"
{
        yyval.elem = yyvsp[0].elem;
    ;
    break;}
case 18:
#line 137 "structfe.y"
{
        char * temp = new_temp();
        printf("Yacc code 3adrs:%s = %s + %s;\n", temp, yyvsp[-2].elem->code, yyvsp[0].elem->code);
        Element * e = malloc(sizeof(Element));
        e->type = TYPE_INT;
        e->code = temp;
        yyval.elem = e;
    ;
    break;}
case 19:
#line 145 "structfe.y"
{
        char * temp = new_temp();
        printf("Yacc code 3adrs:%s = %s - %s;\n", temp, yyvsp[-2].elem->code, yyvsp[0].elem->code);
        Element * e = malloc(sizeof(Element));
        e->type = TYPE_INT;
        e->code = temp;
        yyval.elem = e;
    ;
    break;}
case 20:
#line 156 "structfe.y"
{
        yyval.elem = yyvsp[0].elem;
    ;
    break;}
case 21:
#line 159 "structfe.y"
{
        char *temp = new_temp();
        printf("Yacc code 3adrs:%s = (%s < %s);\n", temp, yyvsp[-2].elem->code, yyvsp[0].elem->code);
        Element *e = malloc(sizeof(Element));
        e->type = TYPE_INT;
        e->code = temp;
        yyval.elem = e;
    ;
    break;}
case 22:
#line 167 "structfe.y"
{
        char *temp = new_temp();
        printf("Yacc code 3adrs:%s = (%s > %s);\n", temp, yyvsp[-2].elem->code, yyvsp[0].elem->code);
        Element *e = malloc(sizeof(Element));
        e->type = TYPE_INT;
        e->code = temp;
        yyval.elem = e;
    ;
    break;}
case 23:
#line 175 "structfe.y"
{
        char *temp = new_temp();
        printf("Yacc code 3adrs:%s = (%s <= %s);\n", temp, yyvsp[-2].elem->code, yyvsp[0].elem->code);
        Element *e = malloc(sizeof(Element));
        e->type = TYPE_INT;
        e->code = temp;
        yyval.elem = e;
    ;
    break;}
case 24:
#line 183 "structfe.y"
{
        char *temp = new_temp();
        printf("Yacc code 3adrs:%s = (%s >= %s);\n", temp, yyvsp[-2].elem->code, yyvsp[0].elem->code);
        Element *e = malloc(sizeof(Element));
        e->type = TYPE_INT;
        e->code = temp;
        yyval.elem = e;
    ;
    break;}
case 25:
#line 195 "structfe.y"
{
        yyval.elem = yyvsp[0].elem;
    ;
    break;}
case 26:
#line 198 "structfe.y"
{
        yyval.elem = yyvsp[-2].elem;
    ;
    break;}
case 27:
#line 201 "structfe.y"
{
        yyval.elem = yyvsp[-2].elem;
    ;
    break;}
case 28:
#line 207 "structfe.y"
{
        yyval.elem = yyvsp[0].elem;
    ;
    break;}
case 29:
#line 210 "structfe.y"
{
        yyval.elem = yyvsp[-2].elem;
    ;
    break;}
case 30:
#line 216 "structfe.y"
{
        yyval.elem = yyvsp[0].elem;
    ;
    break;}
case 31:
#line 219 "structfe.y"
{
        yyval.elem = yyvsp[-2].elem;
    ;
    break;}
case 32:
#line 225 "structfe.y"
{
        yyval.elem = yyvsp[0].elem;
    ;
    break;}
case 33:
#line 228 "structfe.y"
{
        printf("yacc code 3adrs:%s = %s;\n", yyvsp[-2].elem->code, yyvsp[0].elem->code);
        yyval.elem = yyvsp[-2].elem;
    ;
    break;}
case 34:
#line 232 "structfe.y"
{
        printf("yacc code 3adrs:%s > %s;\n", yyvsp[-2].elem->code, yyvsp[0].elem->code);
        yyval.elem = yyvsp[-2].elem;
    ;
    break;}
case 35:
#line 236 "structfe.y"
{
        printf("yacc code 3adrs:%s < %s;\n", yyvsp[-2].elem->code, yyvsp[0].elem->code);
        yyval.elem = yyvsp[-2].elem;
    ;
    break;}
case 36:
#line 240 "structfe.y"
{
        printf("yacc code 3adrs:%s <= %s;\n", yyvsp[-2].elem->code, yyvsp[0].elem->code);
        yyval.elem = yyvsp[-2].elem;
    ;
    break;}
case 37:
#line 244 "structfe.y"
{
        printf("yacc code 3adrs:%s >= %s;\n", yyvsp[-2].elem->code, yyvsp[0].elem->code);
        yyval.elem = yyvsp[-2].elem;
    ;
    break;}
case 38:
#line 252 "structfe.y"
{
        printf("yacc code 3adres:%s %s;\n", yyvsp[-2].elem->code, yyvsp[-1].elem->code);
        insert_symbol_toptas(tas, yyvsp[-1].elem->code, yyvsp[-2].elem->type);
    ;
    break;}
case 39:
#line 259 "structfe.y"
{
        yyval.elem = yyvsp[0].elem;
    ;
    break;}
case 40:
#line 262 "structfe.y"
{
        yyval.elem = yyvsp[0].elem;
    ;
    break;}
case 41:
#line 268 "structfe.y"
{
        Element * e = malloc(sizeof(Element));
        e->type = TYPE_VOID;
        e->code = "void";
        yyval.elem = e;
    ;
    break;}
case 42:
#line 274 "structfe.y"
{
        Element * e = malloc(sizeof(Element));
        e->type = TYPE_INT;
        e->code = "int";
        yyval.elem = e;
    ;
    break;}
case 43:
#line 283 "structfe.y"
{
        Element * e = malloc(sizeof(Element));
        e->type = TYPE_STRUCT;
        e->code = "";
        yyval.elem = e;
    ;
    break;}
case 44:
#line 289 "structfe.y"
{
        Element * e = malloc(sizeof(Element));
        e->type = TYPE_STRUCT;
        e->code = "";
        yyval.elem = e;
    ;
    break;}
case 45:
#line 295 "structfe.y"
{
        Element * e = malloc(sizeof(Element));
        e->type = TYPE_STRUCT;
        e->code = "";
        yyval.elem = e;
    ;
    break;}
case 48:
#line 309 "structfe.y"
{
        printf("yacc code 3adres:%s %s;\n", yyvsp[-2].elem->code, yyvsp[-1].elem->code);
    ;
    break;}
case 49:
#line 315 "structfe.y"
{
        yyval.elem = yyvsp[0].elem;
        yyval.elem->code = concat("*", yyvsp[0].elem->code);
    ;
    break;}
case 50:
#line 319 "structfe.y"
{
        yyval.elem = yyvsp[0].elem;
    ;
    break;}
case 51:
#line 325 "structfe.y"
{
        Element * e = malloc(sizeof(Element));
        e->type = TYPE_INT;
        e->code = yyvsp[0].id;
        yyval.elem = e;
    ;
    break;}
case 52:
#line 331 "structfe.y"
{
        yyval.elem = yyvsp[-1].elem;
    ;
    break;}
case 53:
#line 334 "structfe.y"
{
        yyval.elem = yyvsp[-3].elem;
    ;
    break;}
case 54:
#line 337 "structfe.y"
{
        printf("yacc code 3adrs:%s %s(){\n", typesNames[yyvsp[-2].elem->type], yyvsp[-2].elem->code);
        yyval.elem = yyvsp[-2].elem;
    ;
    break;}
case 57:
#line 349 "structfe.y"
{
        yyval.elem->type = yyvsp[-1].elem->type;
        yyval.elem->code = yyvsp[0].elem->code;
    ;
    break;}
case 67:
#line 371 "structfe.y"
{   
        expandTas(&tas);        
    ;
    break;}
case 68:
#line 377 "structfe.y"
{
        printf("Yacc code 3adrs:}\n");
        popTas(&tas);
    ;
    break;}
case 75:
#line 399 "structfe.y"
{
        printf("Yacc code 3adrs: IF (%s) THEN\n", yyvsp[-2].elem->code);
    ;
    break;}
case 76:
#line 402 "structfe.y"
{
        printf("Yacc code 3adrs: IF (%s) ELSE %s\n", yyvsp[-4].elem->code, yyvsp[-2].elem->code);
    ;
    break;}
case 79:
#line 414 "structfe.y"
{
        printf("yacc code 3adrs:return;\n");
    ;
    break;}
case 80:
#line 417 "structfe.y"
{
        printf("yacc code 3adrs:return %s;\n", yyvsp[-1].elem->code);
    ;
    break;}
}

#line 839 "/usr/share/bison++/bison.cc"
   /* the action file gets copied in in place of this dollarsign  */
  yyvsp -= yylen;
  yyssp -= yylen;
#ifdef YY_parse_LSP_NEEDED
  yylsp -= yylen;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

  *++yyvsp = yyval;

#ifdef YY_parse_LSP_NEEDED
  yylsp++;
  if (yylen == 0)
    {
      yylsp->first_line = YY_parse_LLOC.first_line;
      yylsp->first_column = YY_parse_LLOC.first_column;
      yylsp->last_line = (yylsp-1)->last_line;
      yylsp->last_column = (yylsp-1)->last_column;
      yylsp->text = 0;
    }
  else
    {
      yylsp->last_line = (yylsp+yylen-1)->last_line;
      yylsp->last_column = (yylsp+yylen-1)->last_column;
    }
#endif

  /* Now "shift" the result of the reduction.
     Determine what state that goes to,
     based on the state we popped back to
     and the rule number reduced by.  */

  yyn = yyr1[yyn];

  yystate = yypgoto[yyn - YYNTBASE] + *yyssp;
  if (yystate >= 0 && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTBASE];

  YYGOTO(yynewstate);

YYLABEL(yyerrlab)   /* here on detecting error */

  if (! yyerrstatus)
    /* If not already recovering from an error, report this error.  */
    {
      ++YY_parse_NERRS;

#ifdef YY_parse_ERROR_VERBOSE
      yyn = yypact[yystate];

      if (yyn > YYFLAG && yyn < YYLAST)
	{
	  int size = 0;
	  char *msg;
	  int x, count;

	  count = 0;
	  /* Start X at -yyn if nec to avoid negative indexes in yycheck.  */
	  for (x = (yyn < 0 ? -yyn : 0);
	       x < (sizeof(yytname) / sizeof(char *)); x++)
	    if (yycheck[x + yyn] == x)
	      size += strlen(yytname[x]) + 15, count++;
	  msg = (char *) malloc(size + 15);
	  if (msg != 0)
	    {
	      strcpy(msg, "parse error");

	      if (count < 5)
		{
		  count = 0;
		  for (x = (yyn < 0 ? -yyn : 0);
		       x < (sizeof(yytname) / sizeof(char *)); x++)
		    if (yycheck[x + yyn] == x)
		      {
			strcat(msg, count == 0 ? ", expecting `" : " or `");
			strcat(msg, yytname[x]);
			strcat(msg, "'");
			count++;
		      }
		}
	      YY_parse_ERROR(msg);
	      free(msg);
	    }
	  else
	    YY_parse_ERROR ("parse error; also virtual memory exceeded");
	}
      else
#endif /* YY_parse_ERROR_VERBOSE */
	YY_parse_ERROR("parse error");
    }

  YYGOTO(yyerrlab1);
YYLABEL(yyerrlab1)   /* here on error raised explicitly by an action */

  if (yyerrstatus == 3)
    {
      /* if just tried and failed to reuse lookahead token after an error, discard it.  */

      /* return failure if at end of input */
      if (YY_parse_CHAR == YYEOF)
	YYABORT;

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Discarding token %d (%s).\n", YY_parse_CHAR, yytname[yychar1]);
#endif

      YY_parse_CHAR = YYEMPTY;
    }

  /* Else will try to reuse lookahead token
     after shifting the error token.  */

  yyerrstatus = 3;              /* Each real token shifted decrements this */

  YYGOTO(yyerrhandle);

YYLABEL(yyerrdefault)  /* current state does not do anything special for the error token. */

#if 0
  /* This is wrong; only states that explicitly want error tokens
     should shift them.  */
  yyn = yydefact[yystate];  /* If its default is to accept any token, ok.  Otherwise pop it.*/
  if (yyn) YYGOTO(yydefault);
#endif

YYLABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */

  if (yyssp == yyss) YYABORT;
  yyvsp--;
  yystate = *--yyssp;
#ifdef YY_parse_LSP_NEEDED
  yylsp--;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "Error: state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

YYLABEL(yyerrhandle)

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yyerrdefault);

  yyn += YYTERROR;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != YYTERROR)
    YYGOTO(yyerrdefault);

  yyn = yytable[yyn];
  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrpop);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrpop);

  if (yyn == YYFINAL)
    YYACCEPT;

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting error token, ");
#endif

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  yystate = yyn;
  YYGOTO(yynewstate);
/* end loop, in which YYGOTO may be used. */
  YYENDGOTO
}

/* END */

 #line 1038 "/usr/share/bison++/bison.cc"
#line 436 "structfe.y"


void yyerror(const char *msg) {
    fprintf(stderr, "Erreur de syntaxe : %s à la ligne: %d ???\n", msg, yylineno);
}

int main() {
    initialize_tas(&tas);
    initialize_table(symbol_table);
    addinTas(&tas, symbol_table);

    yyparse();
    return 0;
}
